#!/bin/bash


echo "enter the tool you want to install "
read tool
echo "do you really want to install ${tool} y/n ? "
read input 
if [ "$input" = "y" ]; then 
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install $tool -y
else
echo "ok thank you"
fi
